import tkinter as tk
win=tk.Tk()
win.title("CodeNovaX GUI")
win.config(bg="#0F30D6")
heading=tk.Label(text=" CodeNovaX ",bg="#142CA2",fg="#FFE100",font=("Arial",30,"bold"))
heading.pack(padx=15,pady=15)   
hello=tk.Label(text="\t\t\n Hello Friends this my Own made GUI ",bg="#164A93",fg="white",font=("Arial",24))
hello.pack(padx=20,pady=20)         
Name_Enter=tk.Label(text=" Enter your Name : ",bg="#174A91",fg="white",font=("Arial",18))
Name_Enter.pack(padx=10,pady=10)
get=tk.Entry(bg="#1F5299",fg="white",font=("Arial",18))
get.pack(padx=10,pady=10)
button2=tk.Button(text=" Subscribe ",bg="#0044CC",fg="white",font=("Arial",18),command=lambda:wellcome.config(text=" Well Come to my subscriber : "+get.get()))
button2.pack(padx=10,pady=10)   
wellcome=tk.Label(text="",bg="#002455",fg="white",font=("Arial",23))
wellcome.pack(padx=10,pady=10)  
win.mainloop()